### ISSUE TITLE
Unhandled exception executing command 'gamemode' in plugin AntiAdmin v1.0.1

### ISSUE THREAD

**Issue by thelite0** [ThatAlbaPerson/AntiAdmin#3]
Expected URL scheme 'http' or 'https' but no colon was found

**Comment by ItsMitlit** [comment]
This error will appear when you don't have the correct discord webhook entered/have none.

You can ignore this if you are using Version 1.0.1 as the plugin should still work without it.

This is just an annoyance in the console and will hopefully be resolved in v1.0.2

**Comment by ItsMitlit** [comment]
Did this help with your issue?

**Comment by ItsMitlit** [comment]
Fixed In [Version 1.0.2](https://github.com/ThatAlbaPerson/AntiAdmin/releases/tag/1.0.2)
